name: Chaining - Deploy
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying after build and test!"
